name: Chartpress Publish OSM-sandbox images
on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'development'
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_GITHUB_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Setup git
        run: git config --global user.email "noreply@geocompas.org" && git config --global user.name "Github Action"
      - name: Install Chartpress
        run: |
          pip install chartpress six ruamel.yaml
      - name: Run Chartpress
        run: chartpress --push --publish-chart
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_GITHUB_TOKEN }}
