name: Chartpress Publish OSM-sandbox images
on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'development'
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    permissions:
      contents: write
      packages: write
      pages: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Setup git
        run: git config --global user.email "noreply@geocompas.org" && git config --global user.name "Github Action"
      - name: Install Chartpress
        run: |
          pip install chartpress six ruamel.yaml
      - name: Run Chartpress
        run: chartpress --push --publish-chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
